project:
  type: website
  output-dir: "docs"
  render:
    - index.qmd
    - Results_New_Wind.qmd
    - Seasonality_of_variables.qmd
website:
  title: "Chla Variability of Arctic Ocean"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Results_New_Wind.qmd
        text: Results 
      - href: Seasonality_of_variables.qmd
        text: Seasonality of variables
format:
  html:
    theme:
      - sandstone
    css: styles.css
    toc: true

editor: source


